import { Injectable } from '@nestjs/common';
import json2md from 'json2md';
import type { ExportDataSection } from '@mentor-ai/shared/types';
import type { FormatGenerator, ExportMetadata } from './format-generator.interface';

@Injectable()
export class MarkdownGenerator implements FormatGenerator {
  readonly formatKey = 'MARKDOWN';
  readonly mimeType = 'text/markdown';
  readonly fileExtension = '.md';

  async generate(
    sections: ExportDataSection[],
    metadata: ExportMetadata
  ): Promise<Buffer> {
    const mdData: json2md.DataObject[] = [
      { h1: `Data Export — ${metadata.tenantName}` },
      {
        p: `**Exported by:** ${metadata.userName} (${metadata.userEmail})  \n**Date:** ${metadata.exportDate}`,
      },
    ];

    for (const section of sections) {
      mdData.push({ h2: section.title });

      if (section.itemCount === 0) {
        mdData.push({ p: '_No data available._' });
        continue;
      }

      if (section.items.length > 0) {
        const headers = Object.keys(section.items[0]!);
        const rows = section.items.map((item) =>
          headers.map((h) => String(item[h] ?? ''))
        );
        mdData.push({
          table: { headers, rows },
        });
      }
    }

    mdData.push({
      p: `---\n_Generated by Mentor AI on ${metadata.exportDate}_`,
    });

    const markdown = json2md(mdData);
    return Buffer.from(markdown, 'utf-8');
  }
}
