#!/bin/bash
curl -s -X POST "http://91.98.231.87:3100/execute" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 9b8d2c89d0ff9f2477b9c2b50b4bf1c0a6a01672014cd02d" \
  -d '{
    "message": "I want to discuss architecture with you before implementing. Here is what we plan:\n\n## Current Problem\nRight now we store concept content in PostgreSQL and use a shared Qdrant collection for all tenants. You have no access to the vault or Qdrant. This is wrong.\n\n## Proposed Architecture (Karpathy LLM Wiki pattern)\n\n1. **Per-tenant Obsidian vault** on Hetzner as the KNOWLEDGE BASE (not PostgreSQL). Markdown files with:\n   - raw/ (immutable sources)\n   - wiki/concepts/ (enriched articles — this is what you write)\n   - skills/, instructions/ (agent config)\n   - index.md (fast concept lookup)\n   - SCHEMA.md (structure definition)\n\n2. **Per-tenant Qdrant collection** (concepts-{tenantId}) for semantic search:\n   - Full enriched content as vectors (not summaries)\n   - Metadata: tenantId, departmentTags, tier, confidence, category\n   - You query this for business context per concept\n\n3. **PostgreSQL only for metadata** — id, slug, status, relationships. NOT content.\n\n4. **You (OpenClaw) get direct access** to:\n   - Tenant Qdrant collection (memory_search wired to it)\n   - Tenant vault path on Hetzner (/root/.openclaw-{tenantId}/vault/)\n   - You READ from vault for context, WRITE enriched articles back to vault\n   - After writing, we embed the full content into Qdrant\n\n5. **Orchestrator pattern** you recommended:\n   - Orchestrator session queries Qdrant for state\n   - Spawns one-shot sub-agents for research/content/marketing\n   - Articles written to vault files\n   - Summaries indexed in Qdrant\n   - Session stays flat\n\n## Questions for you:\n1. Does this architecture make sense to you?\n2. How should we configure your memory_search to point to the tenant Qdrant collection?\n3. Should the vault be on your local filesystem (/root/.openclaw-{tenantId}/vault/) so you can read/write directly?\n4. What is the best way to wire your Qdrant access — env var, config file, or tool parameter?\n5. Any concerns or improvements you would suggest?\n6. How do you want to receive the concept enrichment tasks — what format, what context should be included vs queried from Qdrant?",
    "agentId": "main",
    "sessionId": "architecture-discussion-001",
    "timeoutSeconds": 180
  }' --max-time 200
