#!/bin/bash
curl -s -X POST "http://91.98.231.87:3100/execute" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 9b8d2c89d0ff9f2477b9c2b50b4bf1c0a6a01672014cd02d" \
  -d '{
    "message": "We are building this now. I need you to do YOUR side of the configuration. Here is exactly what will happen:\n\n## What I (backend) will do:\n1. During onboarding, create vault at /root/.openclaw-{tenantId}/vault/ with:\n   - SCHEMA.md (article structure + frontmatter format)\n   - instructions/tenant-config.md (business profile, industry, style)\n   - instructions/bootstrap.md (your mandate for this tenant)\n   - index.md (seeded with concept slugs, status: placeholder)\n   - log.md (empty, ready for entries)\n   - wikilink-map.md (slug to file path mapping)\n   - wiki/concepts/ (empty, ready for articles)\n   - wiki/skills/ (empty, ready for learned procedures)\n   - raw/ (empty, ready for research snapshots)\n   - skills/ (symlink to wiki/skills/ for backward compat)\n2. Create Qdrant collection concepts-{tenantId} with per-section chunked vectors\n3. Write Qdrant credentials to /root/.openclaw-{tenantId}/config/qdrant.env\n4. Send enrichment tasks as minimal JSON: {concept, category, tenantId, vaultPath}\n\n## What I need YOU to do:\n1. When you receive a task with vaultPath, READ SCHEMA.md + tenant-config.md + index.md FIRST\n2. Use memory_search or exec curl to query Qdrant for related concepts\n3. Write enriched articles to {vaultPath}/wiki/concepts/{slug}.md\n4. Update index.md after each article\n5. Update log.md with timestamp + action\n6. Save learned procedures to wiki/skills/\n7. Use wikilink-map.md for cross-linking\n\n## Questions:\n1. Can you write a SOUL.md snippet or instructions file that I should place at /root/.openclaw-{tenantId}/agents/main/agent/SOUL.md that tells you to operate in vault mode? What should it say?\n2. For Qdrant access — should I write a helper script at /root/.openclaw-{tenantId}/tools/qdrant-search.sh that you can exec, or can you curl the Qdrant API directly?\n3. Write me the exact SCHEMA.md content you want — the article template with frontmatter format\n4. Write me the exact bootstrap.md template — what you need to know about a new tenant\n5. After I create the vault, should I send you a one-time setup message to initialize, or will you self-configure when you see the first task?",
    "agentId": "main",
    "sessionId": "implementation-plan-001",
    "timeoutSeconds": 180
  }' --max-time 210
