#!/bin/bash
curl -s -X POST "http://91.98.231.87:3100/execute" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 9b8d2c89d0ff9f2477b9c2b50b4bf1c0a6a01672014cd02d" \
  -d '{
    "message": "Continuing our architecture discussion. We built the Karpathy LLM Wiki pattern for your vault. The vault is not just article storage — it is your EXTENDED MEMORY and SKILL REPOSITORY. Here is the full design:\n\n## Vault Structure (per tenant)\n```\n/root/.openclaw-{tenantId}/vault/\n├── raw/           ← immutable sources (web research snapshots, original data)\n├── wiki/concepts/ ← enriched knowledge articles (what you write)\n├── skills/        ← your learned skills and procedures\n├── instructions/  ← tenant-specific config, style, rules\n├── index.md       ← fast lookup catalog\n├── log.md         ← operation log (what was enriched, when, by whom)\n└── SCHEMA.md      ← structure definition\n```\n\n## The Karpathy Pattern (3 layers)\n1. **raw/** — immutable inputs. Web research results, scraped data, user uploads. You never modify raw/.\n2. **wiki/** — your living knowledge. You write, update, cross-link with [[wikilinks]]. This GROWS over time as conversations add insights.\n3. **skills/** — your learned procedures. When you discover a better way to research, write, or analyze for this tenant, you save it as a skill.\n\n## Knowledge Lifecycle (tiers)\n- working → episodic → semantic → procedural\n- Concepts start as working (placeholder), get enriched to semantic, and procedures you learn become procedural knowledge\n\n## Extended Memory\n- After every conversation, valuable insights get CRYSTALLIZED back into wiki/ concepts\n- Your memories are not just in Qdrant vectors — they are in the vault markdown files you can READ\n- When you need context, you READ from vault (precise) or SEARCH Qdrant (semantic)\n\n## Skill Repository\n- skills/ contains procedures you learned: how to research for this industry, what sources work best, what writing style the tenant prefers\n- You UPDATE skills/ when you learn something new\n- Example: skills/research-legal-tech.md — your learned procedure for researching Irish legal tech topics\n\n## Questions:\n1. How would you USE this vault as extended memory during enrichment? Walk me through the flow.\n2. How would skills/ work in practice? When would you read vs write skills?\n3. How should insight crystallization work — after a user conversation, how do you decide what goes back into the vault?\n4. Does this change how you would structure the orchestrator session?\n5. Any improvements to this design?",
    "agentId": "main",
    "sessionId": "architecture-discussion-001",
    "timeoutSeconds": 180
  }' --max-time 210
